// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormController from "./form_controller"
application.register("form", FormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import StepFormController from "./step_form_controller"
application.register("step-form", StepFormController)

import TextareaController from "./textarea_controller"
application.register("textarea", TextareaController)

import ViewChatController from "./view_chat_controller"
application.register("view-chat", ViewChatController)
